version: "3.7"
services:

  db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_LOGIN}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    volumes:
     - db_data:/var/lib/db/data

  bot:
    build: .
    env_file:
      - .env
    container_name: bot
    ports:
      - "8333:8333"
    depends_on:
      - db

volumes:
  db_data: